apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-demo
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: microservices-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/doflamingo721/microservices-demo.git'
    targetRevision: main
    path: helm-chart
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: microservices-demo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3
