# bridge-net.yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: bridge-net
  namespace: microservices-demo
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "br0",
    "isGateway": true,
    "ipam": {
      "type": "static",
      "subnet": "10.10.0.0/24",
      "routes": [],
      "rangeStart": "10.10.0.10",
      "rangeEnd": "10.10.0.20",
      "gateway": "10.10.0.1"
    }
  }'
